version: "3.1"


services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - database
  database:
    restart: always
    network_mode: "host"
#    ports:
#      - "5432:5432"
    image: postgres
    volumes:
      - /home/sanbox/development/golang-projects/english-new-words/docker-storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
      - POSTGRES_DB=english_bot